---
abstract: 'Abbreviate Perl namespaces for the Extreme Perl Golf'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-TLDR
requires:
  File::HomeDir: '0'
  List::MoreUtils: '0'
  Module::CoreList: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/creaktive/Acme-TLDR/issues
  homepage: https://github.com/creaktive/Acme-TLDR
  repository: git://github.com/creaktive/Acme-TLDR.git
version: '0.004'
x_contributors:
  - 'Sergey Romanov <sromanov-dev@yandex.ru>'
